### ISSUE TITLE
Resolve code-style warnings & annotations

### ISSUE THREAD

**Issue by nogic1008** [nogic1008/WritableOptions.Net#69]
Fix or dismiss these warnings & annotations
- [x] [CA1707](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1707): Identifiers should not contain underscores (#72)
- [x] [CA1848](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1848): Use the `LoggerMessage` delegates (#78)
- [x] CS8019: Unnecessary `using` directive (#68)
- [x] [IDE0058](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0058): Remove unnecessary expression value (#70)
- [x] [IDE0065](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0065): `using` directive placement (#68)
- [x] [IDE0160](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/formatting-rules#namespace-options): Convert to block scoped namespace (#68)
